  version: '3.9'

  services:
    app-blue:
      image: jywon1128/dummy-app:${TAG:-latest}
      container_name: app-blue
      ports:
        - 8081:8080
      networks:
        - appnet
      restart: always

    app-green:
      image: jywon1128/dummy-app:${TAG:-latest}
      container_name: app-green
      ports:
        - 8082:8080
      networks:
        - appnet
      restart: always

  networks:
    appnet:
      driver: bridge